### ISSUE TITLE
4.x version

### ISSUE THREAD

**Issue by voledemar** [go-parse/parse#12]
4.x release after solving:
* [ ] #1 Realize environment variables casting
* [ ] #7 time.Duration support in flags parsing
* [ ] #9 Realize configs and environment variables saving

**Comment by voledemar** [comment]
Issue is covered by milestone.
