### ISSUE TITLE
3.0 version

### ISSUE THREAD

**Issue by voledemar** [go-parse/parse#6]
3.x release after solving:
* [ ] #3 Make from type flagValues structure
* [x] #4 Improve README.md
* [ ] #5 Tags improvements
* [ ] #8 Replace from valid package Letter and Digit funcs to unicode package realizations
* [ ] #10 Tests improvements
* [ ] #11 File parsing complex improvements

**Comment by voledemar** [comment]
I think it should be `3.1` cause I do not have time.

**Comment by voledemar** [comment]
Issue is covered by milestone.
